package bulkedin


class ExplicitlyIgnored implements IgnoreSpecification {

    def ignores = [
            "Tatiana Endrjukaite",
            "Laurynas Zubko",
            "Magdalena Firlit",
            "Dalius Gaižutis",
            "Jānis Salenieks",
            "Ilze Tenberga",
            "Martin Villig",
            "Martins Leitass",
            "Raimondas Gaubys",
            "Sabīne Ciemiņa",
            "Oleg Yaroshevich",
            "Jānis Lāma",
            "Rytis Krusinskas",
            "Jekaterina Tarakanova",
            "Kristina Šuklevičienė",
            "Eugenija Juškevičiūtė",
            "Jelena Veide",
            "Uldis Leiterts",
            "Dmitry Demenchoock",
            "Sanda Linde",
            "Marius Sagatavičius",
            "Andrejs Guba",
            "Justas Jankauskas",
            "Darius Grigaliunas ☁ (Strategic networker)",
            "Evaldas Marcinkus",
            "Serhiy Timoshok",
            "Tomas Gedvilas",
            "Ingrida Raziene",
            "Paulius Antonovas",
            "Edgar Fukson",
            "Joana Grigaliūnienė",
            "Antanas Balbata",
            "Robertas Braskys",
            "Henrikas Šavela",
            "Roland Pihlakas",
            "Arnas Žardeckas",
            "Gediminas Misevičius",
            "Nils L.",
            "Alex Zelinsky",
            "Pavel Obod",
            "Vladimir Tarasov",
            "Annija Babre",
            "Nikolajs Panovs",
            "Brigita Gnutone",
            "Mārtiņš Olte",
            "Artjoms Gerasimciks",
            "Mantė Petrauskaitė",
            "Gintaras Slavinskas",
            "Niall Whelehan",
            "Volha Mikuliak",
            "Ramūnas Paškevičius, PMP",
            "Max Lebedev, PMP",
            "Ringo Lepik",
            "Oleg Ivashchenko",
            "Kaspars Kalnins",
            "Olesja Tulaidana",
            "Carlo Becchi",
            "Olga Zaharenko",
            "Harijs Bernans",
            "Erik Bonder",
            "Sergejs Gribs",
            "Svetlana Bozhko",
            "Vasilij Zhukov",
            "maciej sowiński, CSP, CSM, CSPO",
            "Pavel Kazlou",
            "Vladimir Statkevich",
            "Auris Aume",
            "Donata Vaidilaitė",
            "Anna Stefanska",
            "Marija Lencmane",
            "Hemant Vashisth, MBA",
            "Mantas Rameika",
            "Igors Ņikonovs",
            "Dovydas Navickas",
            "Eugene Furs",
            "Anda Auce",
            "Aigars Staks",
            "Solveiga Deksne",
            "Olga Rekke",
            "Mantas Rameika",
            "Andrius Tiskevicius",
            "Roman Bugaev",
            "Kaspar Roost",
            "Dmitry Trifonov",
            "Kristjan Männik",
            "Vadims Jagodins",
            "Raitis Sevelis",
            "Omaras Adi",
            "Kristina Chirkova",
            "Deniss Samoilovs",
            "Dr. Kęstutis Morkūnas",
            "Meren Tamm",
            "Andrey Vakunov",
            "Kaur Klaamann",
            "Ivan Zhamoidzin",
            "Raido Tamar",
            "Priit Potter",
            "Ljubov Bezan"]


    @Override
    boolean satisfies(String fullName) {
        ignores.contains(fullName)
    }
}
